PID: 7664
honu.cs.washington.edu
Job started at Wed Aug 21 13:34:39 PDT 2019
Running patch plausibility analysis under Java-8 on the patch generated by DynaMoth for Bugs.jar::Flink-380ef878::7
patch_plausibility.py script started at Wed Aug 21 13:34:39 PDT 2019
Switched to branch 'bugs-dot-jar_FLINK-1761_380ef878'
Reinitialized existing Git repository in /tmp/DynaMoth_Bugs.jar_Flink_380ef878/.git/
Checking patch flink-runtime/src/main/java/org/apache/flink/runtime/io/network/netty/PartitionRequestClientHandler.java...
Applied patch flink-runtime/src/main/java/org/apache/flink/runtime/io/network/netty/PartitionRequestClientHandler.java cleanly.
There was no 'Please refer to (.*) for the individual test results.' in the maven log file!
Traceback (most recent call last):
  File "/scratch/rjust/critical_review_of_repair_them_all_data/plausibility/patch_plausibility.py", line 175, in <module>
    test, all_tests, failing_tests = utils.test(bugObj, CHECKOUT_DIR, java_home_dir, os.path.join(output_dir, "test.log"))
  File "/scratch/rjust/critical_review_of_repair_them_all_data/java_7_vs_java_8/utils.py", line 180, in test
    xml_files = collect_maven_surefire_xml_files(checkout_dir, rta_test_log_file)
  File "/scratch/rjust/critical_review_of_repair_them_all_data/java_7_vs_java_8/utils.py", line 258, in collect_maven_surefire_xml_files
    assert len(xml_files) > 0
AssertionError
Checkout Bugs.jar_Flink_380ef878
Apply patch ...
Compile Bugs.jar_Flink_380ef878
Run tests on Bugs.jar_Flink_380ef878
patch_plausibility.py has failed!
