---
BugID: OAK-1081
Summary: Node.getNodes throwing exception if user does not have access to any child
  node
Description: "When trying to obtain child iterator via Node.getNodes {{InvalidItemStateException}}
  is thrown if user does not have access to its content\n\n{code:java}\n    @Test\n
  \   public void testGetChildren() throws Exception {\n        deny(path, privilegesFromName(PrivilegeConstants.JCR_ADD_CHILD_NODES));\n
  \       NodeIterator it1 = testSession.getNode(path).getNodes();\n        while(it1.hasNext()){\n
  \           Node n = it1.nextNode();\n            NodeIterator it2 = n.getNodes();\n
  \       }\n    }\n{code}\n\nExecuting above code leads to following exception\n\n{noformat}\njavax.jcr.InvalidItemStateException:
  Item is stale\n\tat org.apache.jackrabbit.oak.jcr.delegate.NodeDelegate.getTree(NodeDelegate.java:827)\n\tat
  org.apache.jackrabbit.oak.jcr.delegate.NodeDelegate.getChildren(NodeDelegate.java:336)\n\tat
  org.apache.jackrabbit.oak.jcr.session.NodeImpl$8.perform(NodeImpl.java:546)\n\tat
  org.apache.jackrabbit.oak.jcr.session.NodeImpl$8.perform(NodeImpl.java:543)\n\tat
  org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate.perform(SessionDelegate.java:125)\n\tat
  org.apache.jackrabbit.oak.jcr.session.ItemImpl.perform(ItemImpl.java:113)\n\tat
  org.apache.jackrabbit.oak.jcr.session.NodeImpl.getNodes(NodeImpl.java:543)\n\tat
  org.apache.jackrabbit.oak.jcr.security.authorization.ReadPropertyTest.testGetChildren(ReadPropertyTest.java:135)\n\tat
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)\n\tat
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)\n\tat
  org.apache.jackrabbit.test.AbstractJCRTest.run(AbstractJCRTest.java:464)\n\tat org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)\n\tat
  org.junit.runner.JUnitCore.run(JUnitCore.java:157)\n\tat com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:77)\n\tat
  com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:195)\n\tat
  com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:63)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native
  Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)\n\tat
  com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)\n{noformat}\n\nThe
  exception is thrown for path {{/testroot/node1/rep:policy}}. \n\nThe issue occurs
  because the {{NodeIterator}} {{it1}} includes {{rep:policy}} and later when its
  child are accessed security check leads to exception. Probably the {{it1}} should
  not include {{rep:policy}} as part of child list and filter it out"
